config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :boards do
    resources :posts
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about', :to => 'pages#about'
  root 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :posts
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new create edit update destroy ]
  before_action :check_user_permission, only: %i[ edit update destroy ]
  before_action :set_posts, only: %i[ show ]

  # GET /boards or /boards.json
  def index
    @boards = Board.all.page(params[:page])
  end

  # GET /boards/1 or /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = Board.new(board_params)
    @board.user = current_user

    respond_to do |format|
      if @board.save
        format.html { redirect_to board_url(@board), notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to board_url(@board), notice: "Board was successfully updated." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    def set_posts
      @posts = @board.posts
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:name)
    end

    def check_user_permission
      if current_user != @board.user
        redirect_to boards_path, alert: "#{current_user.username}, You are no permission to update/delete [#{@board.name}]."
      end
    end
end

app/controllers/pages_controller.rb
require 'json'
require 'socket'
class PagesController < ApplicationController
  def about
    @app = Rails.application.class.name.split(/::/)[0]
    @version = JSON.parse(File.read(Rails.root.join('package.json')))['version']
    @rails = Rails.version
    @ruby = RUBY_VERSION
    @env = Rails.env
    @adapter = ActiveRecord::Base.connection.adapter_name
    @host = Socket.gethostname
    @ip = Socket.ip_address_list.find { |ip| ip.ipv4? && !ip.ipv4_loopback? }.ip_address
    @remote_ip = request.remote_ip
    @time = Time.current.to_s(:long)
    #flash[:alert] = 'Hello Alert!'
    #flash[:info] = 'Hello Info!'
    #flash[:warning] = 'Hello Warning!'
    #flash[:success] = 'Hello Success!'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_board
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :show ]
  before_action :check_user_permission, only: %i[ new create edit update destroy ]

  # GET /posts or /posts.json
  def index
    redirect_to board_path(@board)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = @board.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = @board.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to board_post_path(@board, @post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to board_post_path(@board, @post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to board_posts_path(@board), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:board_id])
    end

    def set_post
      @post = @board.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end

    def check_user_permission
      if current_user != @board.user
        redirect_to board_path(@board), alert: "#{current_user.username}, You are no permission to create/update/delete [#{@post.title}]."
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>Boards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.name %></td>
        <td><%= board.user.username %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="paginate-bar">
  <%= paginate @boards %>
</div>

<br>

<%= link_to 'New Board', new_board_path %>
| <%= link_to 'Home', root_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @board.name %>
</p>

<% if @posts != nil %>
  <hr>
  <h5>Listing Posts</h5>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %>
        <td><%= post.content %>
        <td><%= link_to 'Show', board_post_path(@board, post) %></td>
        <td><%= link_to 'Edit', edit_board_post_path(@board, post) %></td>
        <td><%= link_to 'Destroy', board_post_path(@board, post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <hr>
<% end %>
<br>
<%= link_to 'New Post', new_board_post_path(@board) %> |
<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails501</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/navbar' %>
      <%= yield %>
      <%= render 'shared/footer' %>
      <%= render 'shared/flash' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<hr>
<div style="display:flex; justify-content: center">
  <table>
    <tbody>
      <tr>
        <td><strong>App Name</strong></td>
        <td><strong><%= @app %></strong></td>
      </tr>
      <tr>
        <td>App Version</td>
        <td><%= @version %></td>
      </tr>
      <tr>
        <td>Rails Version</td>
        <td><%= @rails %></td>
      </tr>
      <tr>
        <td>Ruby Version</td>
        <td><%= @ruby %></td>
      </tr>
      <tr>
        <td>Rails Environment</td>
        <td><%= @env %></td>
      </tr>
      <tr>
        <td>Rails Database</td>
        <td><%= @adapter %></td>
      </tr>
      <tr>
        <td>Host</td>
        <td><%= @host %></td>
      </tr>
      <tr>
        <td>Host IP</td>
        <td><%= @ip %></td>
      </tr>
      <tr>
        <td>Remote IP</td>
        <td><%= @remote_ip %></td>
      </tr>
      <tr>
        <td>Current Time</td>
        <td><%= @time %></td>
      </tr>
    </tbody>
  </table>
</div>
<hr>

<%= link_to 'Boards', boards_path %>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :content %>
  <%= form.text_area :content %>
</div>

<div class="actions">
  <%= form.submit %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= form_with(model: @post, local: true, :url => board_post_path(@board, @post)) do |f| %>
  <%= render 'form', form: f %>
<% end %>

<%= link_to 'Show', board_post_path(@board, @post) %> |
<%= link_to 'Back', board_posts_path(@board) %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with(model: @post, local: true, :url => board_posts_path(@board)) do |f| %>
  <%= render 'form', form: f %>
<% end %>

<%= link_to 'Back', board_posts_path(@board) %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_board_post_path(@board, @post) %> |
<%= link_to 'Back', board_posts_path(@board) %>

app/views/shared/_flash.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %> alert-dismissible fade show">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="x"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="container" style="margin-top: 40px;">
  <p class="text-center">Copyright ©2023 Rails501</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class='navbar navbar-light bg-light navbar-expand-lg'>
  <div class='container-fluid'>
    <a class="nav-logo" href="https://rubyonrails.org/" target="_blank" aria-label="Ruby on Rails"></a>
    <%= link_to 'Rails 501', root_path, class: 'navbar-brand ms-5 mb-0 h1 btn btn-outline-danger' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class='collapse navbar-collapse' id="navbarSupportedContent">
      <ul class='navbar-nav ms-auto mb-2 mb-lg-0'>
        <li class="nav-item">
          <%= link_to 'About', '/about', class: 'nav-link' %>
        </li>
        <li class="nav-item">
        </li>
      <% if !current_user %>
        <li class="dropdown">
          <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
           Login  
          </button>
          <ul class="dropdown-menu">
            <li> <%= link_to 'Login', new_user_session_path, class: "dropdown-item" %></li>
            <li> <%= link_to 'Register', new_user_registration_path, class: "dropdown-item" %> </li>
          </ul>
        </li>
      <% else %>
        <li class="dropdown">
          <button class="btn btn-sm btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.username %>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit', edit_user_registration_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: "dropdown-item" %></li>
          </ul>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="card border-white" style="height: 2rem;">
</div>

app/views/shared/_user_nav.html.erb
<div class="user_navigation">
  <% if !current_user %>
    <%= link_to 'Sign in', new_user_session_path %>
    <%= link_to 'Sign up', new_user_registration_path %>
  <% else %>
    Hi! <%= current_user.username %>
    <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
  <% end %>
</div>